name: draw-graph
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Install requirements
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          sudo apt install graphviz
          sudo apt-get install libgraphviz-dev
          pip install -r requirements.txt
          echo "## Installed requirements successfully"
      - name: Fetch data
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc pull data/data.csv --run-cache
          echo "## Data pulled from dvc remote"
      - name: Draw graph
        run: |
          cd scripts 
          python causality_graphing.py
      - name: Write CML report
        run: |
          # Post reports as comments in GitHub PRs
          echo "## Causal Graph for this run" >> report.md
          cml-publish graph.png --md >> report.md
          cml-send-comment report.md
